<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no" />
    <title>Yenching Academy of Perking University</title>
    <link rel="stylesheet" href="/public/css/base.css" />
    <link rel="stylesheet" href="/public/css/style.css" />
    <script type="text/javascript" src="/public/scripts/jquery.main.js"></script>
    <script type="text/javascript" src="/public/scripts/parallaxscroll.js"></script>
    <script type="text/javascript" src="/public/scripts/main.js"></script>
</head>
<body class="body">
    <div class="left-bar">
        LEFT MENU
    </div>
    <div class="right-bar">
        RIGHT MENU
    </div>
    <div class="maincontent">
        <?php echo $this->layout()->content?>
    </div>
    
</body>
</html>