<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no" />
    <title>Yenching Academy of Perking University</title>
    <link rel="stylesheet" href="/public/css/base.css" />
    <link rel="stylesheet" href="/public/css/style.css" />
    <script type="text/javascript" src="/public/scripts/jquery.main.js"></script>
    <script type="text/javascript" src="/public/scripts/parallaxscroll.js"></script>
    <script type="text/javascript" src="/public/scripts/main.js"></script>
</head>
<body class="body">
    <div class="left-bar">
        <ul class="left-bar-menu clearfix">
            <li class="m-item m-item-0"></li>
            <li class="m-item m-item-1"></li>
            <li class="m-item m-item-2"></li>
            <li class="m-item m-item-3"></li>
            <li class="m-item m-item-4"></li>
            <li class="m-item m-item-5"></li>
            <li class="m-item m-item-6"></li>
        </ul>
    </div>
    <div class="right-bar">
    </div>
    <div class="maincontent">
        <?php echo $this->layout()->content?>
    </div>

    <div class="footer">
        <div class="icon"></div>
        <div class="p1">Copyright &copy; The Yenching Academy, Peking University, 
</div>
        <div class="p2">
5 Yiheyuan Road, Haidian District, Beijing, China, Postal Code: 100871  Email: yca@pku.edu.cn</div>
    </div>
    
</body>
</html>