<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no" />
    <title>Yenching Academy of Perking University</title>
    <link rel="stylesheet" href="/public/css/base.css" />
    <link rel="stylesheet" href="/public/css/font/Helveticalight/font.css" />
    <link rel="stylesheet" href="/public/css/font/HelveticaBold/font.css" />
    <link rel="stylesheet" href="/public/css/font/HelveticaNormal/font.css" />
    <link rel="stylesheet" href="/public/css/font/Plantin/font.css" />
    <link rel="stylesheet" href="/public/css/style.css" />
    <link rel="stylesheet" href="/public/css/1200.css" media="screen and max-width(1200)">
    <script type="text/javascript" src="/public/scripts/jquery.main.js"></script>
    <script type="text/javascript" src="/public/scripts/stellar.js"></script>
    <script type="text/javascript" src="/public/scripts/template.js"></script>
    <script type="text/javascript" src="/public/scripts/waypoints.js"></script>
    <script type="text/javascript" src="/public/scripts/easing.js"></script>
    <script type="text/javascript" src="/public/scripts/main.js"></script>
</head>
<body class="body">
    <div class="left-bar ">
        <ul class="left-bar-menu clearfix">
            <li class="m-item m-item-0"></li>
            <li class="m-item m-item-1" data-section="1"><a href="/#home">Home</a></li>
            <li class="m-item m-item-2" data-section="2"><a href="/#academy">academy</a></li>
            <li class="m-item m-item-3" data-section="3"><a href="/#program">program</a></li>
            <li class="m-item m-item-4" data-section="4"><a href="/#residential">residential</a></li>
            <li class="m-item m-item-5" data-section="5"><a href="/#news">news</a></li>
            <li class="m-item m-item-6"></li>
        </ul>
    </div>
    <div class="right-bar ">
    </div>
    <div class="maincontent">
        <?php echo $this->layout()->content?>
    </div>

</body>
</html>