
<div class="s1 s" >
    <div class="wrapper">
        <div class="home">
            <div class="header-tip">
                <div class="logo">
                    <img src="/public/misc/images/logo.png" alt="">
                </div>
                <p class="t font-size-45">
                    The elite <br \> china experience <br \>for future global leaders <br \>
                </p>
            </div>
            <div class="bg">
                <img src="/public/misc/images/pictures/home/1.jpg" class="img-full" alt="">
            </div>
        </div>
    </div>
</div>

<div class="s2 s">
    <div class="wrapper">
        <div class="home">
            <div class="content">
                <div class="star"></div>
                <div class="header">
                    <h1 class="font-size-45">The  Yenching Academy</h1>
                    <div class="line"></div>
                     <p class="c font-size-20">The Yenching Academy is built on the intention to bring our students the real-time development in China. As a prestigious college within Peking University, the Yenching Academy prepares its students to take leading roles to tackle the world’s most challenging issues.</p>
                </div>
                <div class="video">
                    <img src="/public/misc/images/icon_play_video.png" alt="">
                </div>
                <div class="slider">
                    <div class="slider-icon"></div>
                    <ul class="slides">
                        <li class="slide-item slide-item-0 clearfix ">
                            <div class="l">
                                <img class="img-full" src="/public/misc/images/pictures/academy/1.jpg" alt="">
                            </div>
                            <div class="r">
                                <h2 class="font-size-45 hl2">Mission</h2>
                                <h3 class="font-size-25 hl3">To provide an elite Chinese Studies experience</h3>
                                <div class="line"></div>
                                <p class="c">The Yenching Academy provides an extraordinary education experience that draws from western and eastern perspectives; cultivate leaders who will advocate for global progress and cultural understanding.</p>
                            </div>
                        </li>
                        <li class="slide-item slide-item-1 clearfix hideme">
                            <div class="l">
                                <img class="img-full" src="/public/misc/images/pictures/academy/1.jpg" alt="">
                            </div>
                            <div class="r">
                                <h2 class="font-size-45 hl2">Mission</h2>
                                <h3 class="font-size-25 hl3">To provide an elite Chinese Studies experience</h3>
                                <div class="line"></div>
                                <p class="c">The Yenching Academy provides an extraordinary education experience that draws from western and eastern perspectives; cultivate leaders who will advocate for global progress and cultural understanding.</p>
                            </div>
                        </li>
                        <li class="slide-item slide-item-2 clearfix hideme" >
                            <div class="l">
                                <img class="img-full" src="/public/misc/images/pictures/academy/1.jpg" alt="">
                            </div>
                            <div class="r">
                                <h2 class="font-size-45 hl2">Mission</h2>
                                <h3 class="font-size-25 hl3">To provide an elite Chinese Studies experience</h3>
                                <div class="line"></div>
                                <p class="c">The Yenching Academy provides an extraordinary education experience that draws from western and eastern perspectives; cultivate leaders who will advocate for global progress and cultural understanding.</p>
                            </div>
                        </li>
                        <li class="slide-item slide-item-3 clearfix hideme" >
                            <div class="l">
                                <img class="img-full" src="/public/misc/images/pictures/academy/2.jpg" alt="">
                            </div>
                            <div class="r">
                                <h2 class="font-size-45 hl2">message from the leadership</h2>
                                <h3 class="font-size-25 hl3">Message from the President</h3>
                                <div class="line"></div>
                                <p class="c">The Yenching Academy, the most ambitious academic initiative Peking University has launched since the turn of the new century, is dedicated to fostering an environment of learning and research that addresses the need for knowledge, ideas, moral character, and human understanding in the age of diversity, respect, and cooperation. The Yenching Scholars, young talents from across the world, will make the world an ever better place.</p>
                                <div class="signature signature-1"></div>

                                <h3 class="font-size-25 hl3">Message from the Dean</h3>
                                <div class="line"></div>
                                <p class="c">The Yenching Academy is a prestigious college within Peking University. As the focal point of innovative research in the areas of humanities and social sciences, and academic and cultural engagement between its scholars, faculty, and prominent political, business, and thought leaders from across the globe, the Yenching Academy is more than just an academic institution, but rather an “idea incubator”- cultivating the leaders who will make a positive impact on the world.</p>
                                <div class="signature signature-2"></div>
                            </div>
                            <div class="btn-c"><span>mission<div class="b-icon"></div></span></div>
                        </li>
                    </ul>
                    <div class="slider-btns">
                        <ul class="btns">
                            <li class="btn btn-1">
                                <span>about pku<div class="b-icon"></div></span>
                            </li>
                            <li class="btn btn-2"><span>leadership<div class="b-icon"></div></span></li>
                            <li class="btn btn-3"><span>message from leadership<div class="b-icon"></div></span></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="s2 s3 s" >
    <div class="wrapper">
        <div class="home">
            <div class="content">
                <div class="header">
                    <h1 class="font-size-45">Program</h1>
                    <div class="line"></div>
                    <h4 class="font-size-25">The first-of-its-kind Chinese Studies program holds in mainland China.</h4>
                     <p class="c font-size-20">The Yenching Academy offers a 1-year Master of Chinese Studies program (in English) designed to prepare an elite class of future leaders to meet the challenges of the 21st century global landscape.</p>
                </div>
                <div class="video">
                    
                </div>
                <div class="slider">
                    <div class="slider-icon"></div>
                    <ul class="slides">
                        <li class="slide-item slide-item-1 clearfix">
                            <div class="r">
                                <img class="img-full" src="/public/misc/images/pictures/program/1.jpg" alt="">
                            </div>
                            <div class="l">
                                <h2 class="font-size-45 hl2">The program</h2>
                                <div class="line"></div>
                                <div class="c">
                                    <p>All students of the Yenching Academy will be Yenching Scholars.</p>

<p>Yenching Scholars not only engage in and develop their own learning experiences, but also work with the pioneers in their field to develop and apply innovative research in the areas of humanities and social sciences. </p>

<p>This Chinese Studies program integrates interdisciplinary approaches, pluralistic perspectives, and cutting-edge research to equip scholars with a rich understanding of Chinese Studies. Scholars will also build on this rich understanding by gaining expertise in one of six concentrations.</p> 

    <h4 class="font-size-18">Concentrations</h4> 
    <ul>
        <li>Language, Literature and Culture</li>
        <li>History and Archaeology</li>
        <li>Philosophy and Religion</li>
        <li>Public Policy and International Relations</li>
        <li>Economics and Management</li>
        <li>Law and Institutions</li>
    </ul>
 </div>
 <div class="next-icon clearfix">
     <div class="p-icon"></div><div class="next_txt">NEXT </div><div class="n-icon"></div>
 </div>
 <div class="subscribe-form">
     <form class="clearfix" action="<?php echo $this->url(array("controller" => "index", "action" => "subscribe"))?>" method="post" enctype="multipart/form-data" name="subscribe">
         <div class="item item-1">
             <div class="i-icon"></div>
         </div>
         <div class="item item-2">
             <label for="email">submit your email to Get more information</label>
             <input type="text" name="email" placeholder="Email address">
         </div>
         <div class="item item-3">
            <input type="submit" value="SUBMIT"/>
         </div>
     </form>
 </div>
                            </div>
                        </li>
                        <li class="slide-item slide-item-1 clearfix"></li>
                        <li class="slide-item slide-item-1 clearfix"></li>
                    </ul>
                    <div class="slider-btns">
                        <ul class="btns">
                            <li class="btn btn-1">
                                <span>faculty<div class="b-icon"></div></span>
                            </li>
                            <li class="btn btn-2"><span>career development & Alumni Services <div class="b-icon"></div></span></li>
                            <li class="btn btn-3"><span>admissions<div class="b-icon"></div></span></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="s4 s2 s">
    <div class="wrapper">
        <div class="home">
            <div class="content">
                <div class="header">
                    <h1 class="font-size-45">residential college</h1>
                    <div class="line"></div>
                    <h4 class="font-size-25">As a former Imperial Garden, the idyllic Yenching Courtyard is the focal point of student life.</h4>
                     <p class="c font-size-20">The Yenching Academy is located at the Yenching Courtyard on the Peking University campus. With the premises of Yenching Courtyard over 40,000 square meters, 6 historical buildings in the Courtyard have been renovated to provide state-of-the-art teaching and learning facilities. Yenching Scholars will live, learn, collaborate, and engage in an exclusive “community of scholars”.
</p>
                </div>
                <div class="slider">
                    <div class="star"></div>
                    <div class="slideshow">
                        <ul class="slideshow-con">
                            <li class="slideshow-item slideshow-item-1">
                                <img class="img-full" src="/public/misc/images/pictures/residential/1.jpg" alt="">
                            </li>
                            <li class="slideshow-item slideshow-item-1"></li>
                            <li class="slideshow-item slideshow-item-1"></li>
                            <li class="slideshow-item slideshow-item-1"></li>
                            <li class="slideshow-item slideshow-item-1"></li>
                        </ul>
                        <ul class="slideshow-btns">
                            <li class="btnli"></li>
                            <li class="btnli"></li>
                            <li class="btnli"></li>
                            <li class="btnli"></li>
                            <li class="btnli"></li>
                        </ul>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<div class="s5 s">
    <div class="wrapper">
        <div class="home">
            <div class="news-block">
                <div class="block-title clearfix">
                    <h2>NEWS ROOM</h2>
                    <div class="filters-con">
                        <ul class="filters clearfix">
                            <li class="filter filter-1 font-size-18">THE YENCHING ACADEMY </li>
                            <li class="filter filter-2 font-size-18">SENIOR FELLOWS </li>
                            <li class="filter filter-3 filter-last font-size-18">sTUDENTS </li>
                        </ul>
                    </div>
                </div>
                <div class="block-con">
                    <ul class="news-list clearfix">
                        <?php foreach ($this->news as $date =>  $news_items) :?>
                        <li class="news-item news-item-date news-item-<?php echo $key+1?>"><div class="v-c"><?php echo $date ?></div></li>
                        <?php foreach ($news_items as $key => $news_item): ?>
                            <li class="news-item news-item-<?php echo $key+1?>"><img src="<?php echo $news_item["images"]["thumbnail"]?>" alt=""></li>
                        <?php endforeach;?>
                        <?php endforeach;?>
                    </ul>
                    <ul class="pager clearfix">
                        <li class="left-p">
                            <a href="#" class="home"></a>
                            <a href="" class="pre">previous</a>
                        </li>
                        <li class="right-p">
                            <a href="" class="last"></a>
                            <a href="" class="next">Next</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>