
<div class="s1 s" >
    <div class="wrapper">
        <div class="home">Home</div>
    </div>
</div>

<div class="s2 s">
    <div class="wrapper">
        <div class="home">YENCHING ACADEMY</div>
    </div>
</div>

<div class="s3 s" >
    <div class="wrapper">
        <div class="home">MISSION</div>
    </div>
</div>

<div class="s4 s">
    <div class="wrapper">
        <div class="home">RPOGRAM</div>
    </div>
</div>

<div class="s5 s">
    <div class="wrapper">
        <div class="home">THE PROGRAM</div>
    </div>
</div>