
<div class="s1 s " id="home" data-stellar-background-ratio="0.4" data-section="1">
    <div class="wrapper">
        <div class="home-nav" >
            <ul class="clearfix lan-bar">
                <li class="item-1"><a href="#">中文</a></li>
                <li class="item-2"><a href="#">CONTACT US</a></li>
            </ul>
            <div class="more-info hideme">
                <p class="p1">北京市海淀区颐和园路5号 </p>
                <p class="p2">北京大学燕京学堂&nbsp;<span style="font-family:'Helvetica'">100871</span></p>
                <p class="p3">
                    <span class="for-app">For application</span><br />
                    <span class="for-app-mail">yca-admission@pku.edu.cn </span><br />
                    <span class="for-inquiry">For inquiry</span><br />
                    <span class="for-inquiry-mail">yca@pku.edu.cn</span><br />
                </p>
            </div>
        </div>
        <div class="home">
            <div class="header-tip" >
                <div class="logo">
                    <img src="/public/misc/images/logo.png" alt="">
                </div>
                <p class="t font-size-45">
                    Elite Interdisciplinary  <br \>China Studies Experience <br \>for Future Leaders <br \>
                </p>
            </div>
            <div class="bg">
               <!--  <img src="/public/misc/images/pictures/home/1.jpg" class="img-full" alt=""> -->
            </div>
        </div>
    </div>
</div>

<div class="s2 s " id="academy" data-stellar-background-ratio="0.3" data-section="2">
    <div class="wrapper" >
        <div class="home">
            <div class="content" >
                <div class="star" ></div>
                <div class="content-top">
                    <div class="header">
                        <h1 class="font-size-45">The  Yenching Academy</h1>
                        <div class="line"></div>
                         <p class="c font-size-20">The Yenching Academy offers an intensive program of interdisciplinary classroom and field study of Chinese history and culture, as well as real-time issues in China’s development.  As a college integrated within China’s leading university, the Yenching Academy prepares a diverse group of exceptional international and Chinese students with the knowledge of China that they need to fulfill their potential as global citizens and leaders.
                        </p>
                    </div>
                    <div class="video" >
                        <img src="/public/misc/images/icon_play_video-1.png" class="clearfix" alt="">
                    </div>
                </div>

                <div class="slider">
                    <div class="slider-icon"></div>
                    <ul class="slides">
                        <li class="slide-item slide-item-0 clearfix ">
                            <div class="l">
                                <img class="img-full" src="/public/misc/images/pictures/academy/1.jpg" alt="">
                            </div>
                            <div class="r">
                                <div class="r-c">
                                    
                                <h2 class="font-size-45 hl2">Mission</h2>
<!--                                 <h3 class="font-size-25 hl3">To provide an elite <br />China Studies experience.</h3>
 -->                                <div class="line"></div>
                                <p class="c">To equip outstanding young scholars with a broad, interdisciplinary knowledge of China that reflects both Chinese and international perspectives, and to cultivate leaders who will advocate for global progress and cultural understanding.</div>
                            </div>
                        </li>
                        <li class="slide-item slide-item-1 clearfix hideme">
                            <div class="l">
                                <img class="img-full" img-src="/public/misc/images/pictures/academy/4.jpg" alt="">
                            </div>
                            <div class="r">
                                <div class="r-c"><h2 class="font-size-45 hl2">about PKU</h2>
<!--                                 <h3 class="font-size-25 hl3">Peking University has been  
at the forefront of China’s  
modernization and
social progress since 1898.</h3> -->
                                <div class="line"></div>
                                <p class="c">Peking University (PKU), established in 1898 is renowned for its tradition of academic excellence as well as the roles it has played at the forefront of China’s modernization and social progress.</p></div>
                                <a class="btn-pk" href="http://english.pku.edu.cn" target="_blank">PKU WebSite</a>
                            </div>
                            <div class="btn-c">
                              <div class="btn-item btn-item-2"><span><img src="/public/misc/tab/academy-tab3.png" alt="" /></span></div>

                                <div class="btn-item btn-item-3"><span><img src="/public/misc/tab/academy-tab2.png" alt="" /></span></div>

                                <div class="btn-item btn-item-0"><span><img src="/public/misc/tab/academy-tab1.png" alt="" /></span></div>
                            </div>
                        </li>
                        <li class="slide-item slide-item-2 clearfix hideme" >
                            <div class="l">
                                <img class="img-full" img-src="/public/misc/images/pictures/academy/3.jpg" alt="">
                            </div>
                            <div class="r">
                                <div class="r-c">
                                <h2 class="font-size-45 hl2">leadership</h2>
                                <div class="line"></div>
                                <p class="c">The Yenching Academy has assembled an acclaimed advisory board made up of scholars and thought leaders who have a strong focus on China. Our advisory board provides strong support to Yenching Scholars in their future endeavors.</p>
                                <ul style="font-size:1.3em;">
                                    <li id="deans-btn"><a href="javascript:void(0)" style=" color: #ffffff;text-decoration: underline;">Deans</a></li>
                                    <li>International Academic Advisory Council</li>
                                </ul></div>
                            </div>
                            <div class="btn-c">
                                <div class="btn-item btn-item-3"><span><img src="/public/misc/tab/academy-tab2.png" alt="" /></span></div>
                                <div class="btn-item btn-item-0"><span><img src="/public/misc/tab/academy-tab1.png" alt="" /></span></div>
                            </div>
                        </li>
                        <li class="slide-item slide-item-3 clearfix hideme" >
                            <div class="l">
                                <img class="img-full" img-src="/public/misc/images/pictures/academy/2.jpg" alt="">
                            </div>
                            <div class="r">
                                <div class="r-c">
                                <h2 class="font-size-45 hl2">message from the leadership</h2>
                                <h3 class="font-size-25 hl3">Message from the President</h3>
                                <div class="line"></div>
                                <p class="c">The Yenching Academy, the most ambitious academic initiative Peking University has launched since the turn of the new century, is dedicated to fostering an environment of learning and research that addresses the need for knowledge, ideas, moral character, and human understanding in the age of diversity, respect, and cooperation. The Yenching Scholars, young talents from across the world, will make the world an ever better place.</p>
                                <div class="signature signature-1"></div>

                                <h3 class="font-size-25 hl3">Message from the Dean</h3>
                                <div class="line"></div>
                                <p class="c">The Yenching Academy is a prestigious college within Peking University. As the focal point of innovative research in the areas of humanities and social sciences, and academic and cultural engagement between its scholars, faculty, and prominent political, business, and thought leaders from across the globe, the Yenching Academy is more than just an academic institution, but rather an “idea incubator”- cultivating the leaders who will make a positive impact on the world.</p>
                                <div class="signature signature-2"></div></div>
                            </div>
                            <div class="btn-c">
                                <div class="btn-item btn-item-0"><span><img src="/public/misc/tab/academy-tab1.png" alt="" /></span></div>
                            </div>
                        </li>
                    </ul>
                    <div class="slider-btns">
                        <ul class="btns">
                            <li class="btn btn-1" >
                              <span><img src="/public/misc/tab/academy-tab4.png" alt="" /></span>
                            </li>
                            <li class="btn btn-2">
                               <span><img src="/public/misc/tab/academy-tab3.png" alt="" /></span>
                            </li>
                            <li class="btn btn-3">
                               <span><img src="/public/misc/tab/academy-tab2.png" alt="" /></span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="s2 s3 s " id="program" data-stellar-background-ratio="0.5" data-section="3">
    <div class="wrapper">
        <div class="home">
            <div class="content">
                <div class="content-top">
                    <div class="header">
                        <h1 class="font-size-45">Program</h1>
                        <div class="line"></div>
                         <p class="c font-size-20">The Yenching Academy offers a 1-year Master of China Studies program (in English) designed to prepare an elite class of future leaders to meet the challenges of the 21st century global landscape.</p>
                    </div>
                </div>
                <div class="slider">
                    <div class="slider-icon"></div>
                    <ul class="slides">
                        <li class="slide-item slide-item-0 clearfix ">
                            <div class="r">
                                <div class="r-c">
                                        <h2 class="font-size-45 hl2"> program</h2>
                                        <div class="line"></div>
                                        <div class="c">
                                            <div class="r-c-slide r-c-slide-1 ">
                                                <p>The Yenching Academy offers international students a one-year Master of Arts in China Studies degree program. Academy courses will be available in both English and Chinese.  It will be possible for international students to complete their degrees with courses taught in English. Chinese language study will be required for all international students; those with an advanced level of Chinese will be encouraged to take courses taught in Chinese.</p>
                                                <h4 class="font-size-18"><b>Curriculum</b></h4>
                                                    <p>Approaching the study of China from multiple perspectives and disciplines, the program will help equip Yenching Scholars with a nuanced understanding of China’s rich civilization and its complexities today. The curriculum will range horizontally across various fields of study in the humanities and social sciences, and vertically through Chinese history.  Some courses will address a theme, such as China’s Population, that will necessitate a team teaching approach by faculty from the departments of Sociology, History, Geography, Anthropology, and Government, for example.  Overall, courses will fall into the following six broad categories: Literature and Culture; History and Archaeology; Philosophy and Religion; Public Policy and International Relations; Economics and Management; and Law and Society.  </p>
                                                    <p class="p2">
                                                    Yenching Scholars will not only be engaged in their own learning experiences, but will also have opportunities to work with the faculty to develop and apply innovative research in humanities and social sciences.
                                                    </p>
                                                
                                            </div>
                                            <div class="r-c-slide r-c-slide-2 r-c-slide-last hideme">
                                                <h5 class="slide-l-t">The Yenching Learning Experience</h5>
                                                <p>Yenching Scholars will also be deeply immersed into Chinese culture through field excursions and an intensive Chinese language program taken along within their degree studies. Further, Yenching Scholars have access to prominent guest lectures, world-renowned visiting faculty, visits to leading domestic and international companies, organizations, and government institutions, and special seminars.  Scholars will be required to enrich their academic knowledge outside the classroom by completing an internship or conducting a Field Study guided by a faculty mentor.  A Master’s thesis with oral defense is required for the degree.</p>
                                                <ul>
                                                    <li>
                                                        <h5 class="slide-l-t">Internship</h5>
                                                        <p>Scholars can gain practical “hands-on” learning experience at one of Yenching Academy’s partners -- leading international and domestic corporations, government institutions, and NGOs.</p>
                                                    </li>
                                                    <li>
                                                        <h5 class="slide-l-t">Field Study</h5>
                                                        <p>Rather than limiting research to the confinements of the classroom, Yenching Scholars will participate in field studies around China, in which they engage in on-site research projects in their area of concentration with a faculty member. </p>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div class="next-icon clearfix">
                                            <div class="p-icon"></div>
                                            <div class="next_txt"><div class="btn" data-nt="NEXT" data-pt="PREVIOUS">NEXT</div></div>
                                            <div class="n-icon n-icon-on"></div>
                                        </div>
                                        <div class="subscribe-form">
                                            <form class="clearfix" action="<?php echo $this->url(array("controller" => "index", "action" => "subscribe"))?>" method="post" enctype="multipart/form-data" name="subscribe">
                                                <div class="item item-1">
                                                    <div class="i-icon"></div>
                                                </div>
                                                <div class="item item-2">
                                                    <label for="email">submit your email to Get more information</label>
                                                    <input type="text" name="email" placeholder="Email address">
                                                </div>
                                                <div class="item item-3">
                                                    <input type="submit" value="SUBMIT"/>
                                                </div>
                                            </form>
                                        </div>
                                </div>
                            </div>
                            <div class="l">
                                <img class="img-full" src="/public/misc/images/pictures/program/1.jpg" alt="">
                            </div>
                        </li>
                        <li class="slide-item slide-item-1 clearfix hideme">
                                    <div class="r">
                                        <div class="r-c">
                                                <h2 class="font-size-45 hl2">faculty</h2>
                                                <div class="c">
                                                    <p>20: internationally reputed scholars </p>
                <p>30: renowned and influential PKU scholars</p>
                <p>20: visiting senior fellows</p>
                                                    <div class="line line-c"></div>
                                                    <span>The Yenching Academy faculty will be comprised of pioneering researchers and practitioners with a diversity of academic backgrounds, research expertise, and experience. They are passionate about making a positive global impact, and dedicated to teaching and research excellence. </span>
                                                </div>
                                        </div>
                                    </div>
                                    <div class="l">
                                        <img class="img-full" img-src="/public/misc/images/pictures/program/2.jpg" alt="">
                                    </div>
                                    <div class="btn-c">
                                        <div class="btn-item btn-item-0">
                                          <span><img src="/public/misc/tab/program-tab1.png" alt="" /></span>
                                        </div>
                                    </div>
                        </li>
                        <li class="slide-item slide-item-2 clearfix hideme">
                            <div class="r">
                                <div class="r-c"><div class="r-c-c">
                                    <h2 class="font-size-45 hl2">career development & <br /> Alumni Services</h2>
                                    <div class="line"></div>
                                    <div class="c">
                                        <p>The Yenching Academy has a dedicated Career Development and Alumni Services Office, which will guide scholars in their career planning, as well as when they join the Peking University alumni network around the world. </p>
                                     </div></div>
                                </div>
                            </div>
                            <div class="l">
                                <img class="img-full" img-src="/public/misc/images/pictures/program/3.jpg" alt="">
                            </div>
                            <div class="btn-c">
                                <div class="btn-item btn-item-0">
                                  <span><img src="/public/misc/tab/program-tab1.png" alt="" /></span>
                                </div>
                                <div class="btn-item btn-item-1">
                                  <span><img src="/public/misc/tab/program-tab2.png" alt="" /></span>
                                </div>
                            </div>
                        </li>
                        <li class="slide-item slide-item-3 clearfix hideme">
                            <div class="r">
                               <div class="r-c">
                                     <h2 class="font-size-45 hl2">ADMISSIONS</h2>
                                     <div class="line"></div>
                                     <div class="c">
                                        <div class="r-c-slide r-c-slide-1">
                                            <p>
                                                The inaugural class of 100 Yenching Scholars will begin in  September, 2015.  Approximately 65 percent will be international students; the remaining 35 percent will be from China mainland.  Yenching Scholars will be a diverse group of talented young leaders who demonstrate academic excellence, leadership, innovative thought, and a commitment to the betterment of society.
                                            </p>
                                            <ul>
                                                <li>
                                                    <b>SCHOLARSHIPS</b>
                                                    <p>Yenching Scholars receive a full tuition scholarship, accommodation in the residential college, and a stipend to cover living expenses.</p>
                                                </li>
                                                <li class="li-3">
                                                    <b>APPLICATION DEADLINE</b>
                                                    <ul style="margin-top: -7px">
                                                        <li style="
    list-style: none;
">
                                                            <b style="
    text-decoration: underline;
    font-size: 1em;
    font-weight: normal;
">International Students</b>
                                                            <p>Applications are open now for candidates who will hold a Bachelor’s degree and be 25 years of age or younger in 2015.  Those applications made before October 30, 2014 will be eligible for early admission.  The final deadline for applications is January 31, 2015.
</p>
                                                        </li>
                                                        <li style="
    list-style: none;
">
                                                            <b style="
    font-weight: normal;
    font-size: 1em;
    text-decoration: underline;
">Chinese Students</b>
                                                            <p>
In order to help select the approximately 35 percent of the student cohort who will be from China, the Yenching Academy holds summer camps for Chinese candidates who will be graduating from their undergraduate programs in the following year.  The first such camp was held from August 19 to 22, 2014. Admission decisions for participants in this camp will be sent to applicants mid September. Please visit <a target="_blank" href="http://grs.pku.edu.cn/tzgg/40110.htm" style=" color: #b00039;">here</a>.
                                                            </p>
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li class="li-2">
                                                    <b>VISA INFORMATION </b>
                                                    <p>The Yenching Academy Administration Office and Office of International Relations at Peking University will assist you in this process and ensure that you have all the proper documentation. <a  target="_blank"  href="http://www.isd.pku.edu.cn/index.php?m=content&c=index&a=lists&catid=179" style=" color: #b00039;">here</a> for more information. </p>
                                                </li>
                                            </ul>
                                        </div>
                                        <div class="r-c-slide r-c-slide-2 r-c-slide-last hideme">
                                            <p>
                                            <ul>
                                               <li>Prospective Yenching Scholars</li>
                                               <li>Bachelor’s degree in any field</li>
                                               <li>Maximum age 25 in 2015</li>
                                               <li>Outstanding academic record</li>
                                               <li>Demonstrated leadership skills</li>
                                               <li>Active in extracurricular activities</li>
                                               <li>Active community engagement and a strong sense of social responsibility</li>
                                               <li>Strong moral character</li>
                                               <li>Demonstrated interest in exploring diverse cultures, in particular about China and the Asia Pacific region</li>
                                               <li>Demonstrated English Proficiency</li>
                                               <li>The inaugural class of 100 Yenching Scholars will be a diverse group of outstanding young people from around the world, approximately 65% from outside China, and 35% from China</li>
                                            </ul>
                                            </p>
                                        </div>
                                     </div>
                                        <div class="next-icon-c clearfix"><div class="next-icon clearfix">
                                            <div class="p-icon"></div>
                                            <div class="next_txt"><div class="btn" data-nt="Prospective Yenching Scholars" data-pt="Go Back">Prospective Yenching Scholars</div></div>
                                            <div class="n-icon n-icon-on"></div>
                                        </div>
                                        <div class="apply-btn clearfix"><a href="javascript:void(0)">Apply Now</a></div></div>
                               </div>
                            </div>
                            <div class="l">
                                <img class="img-full" img-src="/public/misc/images/pictures/program/4.jpg" alt="">
                            </div>
                            <div class="btn-c">
                                <div class="btn-item btn-item-0">
                               <span><img src="/public/misc/tab/program-tab1.png" alt="" /></span>
                                </div>
                                <div class="btn-item btn-item-1">
                               <span><img src="/public/misc/tab/program-tab2.png" alt="" /></span>
                                </div>
                                <div class="btn-item btn-item-2">
                                  <span><img src="/public/misc/tab/program-tab3.png" alt="" /></span>
                                </div>
                            </div>
                        </li>
                    </ul>
                    <div class="slider-btns">
                        <ul class="btns">
                            <li class="btn btn-1">
                               <span><img src="/public/misc/tab/program-tab2.png" alt="" /></span>
                            </li>
                            <li class="btn btn-2">
                              <span><img src="/public/misc/tab/program-tab3.png" alt="" /></span>
                            </li>
                            <li class="btn btn-3">
                              <span><img src="/public/misc/tab/program-tab4.png" alt="" /></span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="s4 s2 s " id="residential" data-stellar-background-ratio="0.1" data-section="4">
    <div class="wrapper">
        <div class="home">
            <div class="content">
                <div class="header">
                    <h1 class="font-size-45">Campus Facilities</h1>
                    <div class="line"></div>
                    <!-- <h4 class="font-size-25">As a former Imperial Garden, the idyllic Jing-Yuan Courtyard is the focal point of student life.</h4>
 -->                     <p class="c font-size-20">The Yenching Academy classrooms and offices will be located in the Jing Yuan Courtyard in the heart of the Peking University campus. A former Imperial Garden, the Jing Yuan Courtyard is home to six historical landmark buildings that will be renovated in strict accordance with government guidelines on cultural preservation.  Yenching Scholars and visiting faculty will reside nearby in dormitory facilities that will feature common lounges, a library, and cafeteria. Yenching Scholars will live, learn, collaborate, and engage in a “community of scholars” that is at the same time very much a part of Peking University life.</p>
                </div>
                <div class="slider">
                    <div class="star"></div>
                    <div class="slideshow">
                        <ul class="slideshow-con">
                            <li class="slideshow-item slideshow-item-1 bg-style"  data-stellar-background-ratio="0" bg-style="background-image:url(/public/misc/images/pictures/residential/1.jpg)">
                            </li>
                            <li class="slideshow-item slideshow-item-2 bg-style" data-stellar-background-ratio="0" bg-style="background-image:url(/public/misc/images/pictures/residential/2.jpg)">
                            </li>
                            <li class="slideshow-item slideshow-item-3 bg-style" data-stellar-background-ratio="0" bg-style="background-image:url(/public/misc/images/pictures/residential/3.jpg)">
                            </li>
                            <li class="slideshow-item slideshow-item-4 bg-style" data-stellar-background-ratio="0" bg-style="background-image:url(/public/misc/images/pictures/residential/4.jpg)">
                            </li>
                        </ul>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<div class="s7 s" id="news-block-2" data-stellar-background-ratio="0.5" data-section="5">
  <div class="wrapper">
    <div class="news-block">
      <div class="news-block-list-con">
        <div class="block-title"><h2><?php echo "News Room"?></h2></div>
      
        <div class="block-content  clearfix">
            <?php $i = 0;?>
            <?php foreach ($this->categories as $key => $category) :?>
            <?php $newsList = $category['content'];?>
            <?php $firstNews = array_shift($newsList);?>
              <div data-cid="<?php echo $key?>" data-category="<?php echo $category['name'] ?>" class="blocks blocks-<?php echo $i + 1?> <?php if (count($this->categories) == $i + 1) echo "blocks-last"; ?> clearfix">
                <div class='wrapper' data-name='all'><div class="items-con"><div class="items clearfix" data-page="1">
                  <div class="item-1 <?php echo $firstNews["news_id"] == '16'  ? 'no-hover': ''; ?>" data-newsid="<?php echo $firstNews["news_id"] == '16' ? '': $firstNews["news_id"]?>" data-title="<?php echo $firstNews["title"]?>">
                    <img src="<?php echo $firstNews["images"]["thumbnail"]?>" alt="" />
                    <div class="con">
                      <div class="category"><?php echo $category['name']?> <span class="star"></span></div>
                      <div class="p">
                        <span><?php echo $firstNews["title"]?></span>
                      </div>
                    </div>
                  </div>
                  <?php foreach ($newsList as $index => $news): ?>
                    <div data-newsid="<?php echo $news["news_id"]?>" data-title="<?php echo $news["title"]?>" class="item item-<?php echo $index + 2?>">
                      <img src="<?php echo $news["images"]["thumbnail"]?>" alt="" />
                    </div>
                  <?php endforeach;?>
                </div></div>
                <?php $count = $category['total']; ?>
                <?php $items_of_page = 7;?>
                <?php $page_num = $count % $items_of_page === 0 ? $count / $items_of_page : intval($count /$items_of_page)  + 1;?>
                <div class="block-pager" data-maxpage="<?php echo $page_num?>">
                  <?php if (!empty($category['children'])) : ?>
                    <ul class='category-pager clearfix'>
                        <li class="pager-link pager-first active" data-cid='<?php echo $key?>'>All</li>
                        <?php foreach ($category['children'] as $ii => $child_term): ?>
                        <li class="pager-link pager-<?php echo $ii?>" data-cid='<?php echo $ii?>'><?php echo $child_term['name']?></li>
                        <?php endforeach;?>
                    </ul>
                  <?php endif;?>
                  <ul class="pager clearfix">
                    <li class="pager-link pager-first"><< </li>
                    <li class="pager-link pager-prev"><</li>
                    <?php for ($page_index = 0; $page_index < $page_num; $page_index++): ?>
                      <li class="pager-link pager-<?php echo $page_index + 1 ?> <?php echo $page_index == 0 ? "active": ""?>" data-index="<?php echo $page_index + 1?>"> <?php echo $page_index + 1?> </li>
                    <?php endfor;?>
                    <li class="pager-link pager-next">> </li>
                    <li class="pager-link pager-last">>></li>
                  </ul>
                </div>
              </div>
            </div>
              <?php $i += 1;?>
            <?php endforeach;?>
          </div>
      </div>
    </div>
  </div>
</div>

<div class="s6 s" id="footer" data-stellar-background-ratio="0.5" data-section="6">
    <div class="footer">
        <div class="icon"><img src="/public/misc/images/news_home_footer_logo.png" alt=""></div>
        <div class="p1">Copyright &copy; The Yenching Academy, Peking University, </div>
        <div class="p2">5 Yiheyuan Road, Haidian District, Beijing, China, Postal Code: 100871  Email: <a href="mailto:yca@pku.edu.cn" style="color:#fff">yca@pku.edu.cn</a></div>
    </div>
</div>

<div id="template-news-item" style="display:none">
    <li class="news-item news-item-{{id}}" data-title="{{title}}" data-newsid="{{news_id}}"><img class="img-full" src="{{{thumbnail}}}?>" alt=""></li>
</div>

<div id="template-news-date" style="display:none">
  <li class="news-item news-item-date">
    <div class="v-c">
      <span><?php echo $date ?></span>
      <img src="/public/misc/images/news_bg.png" class="img-full" alt="" />
    </div>
  </li>
</div>

<div id="template-news-list" style="display:none">{{{newsrender}}}</div>

<div id="template-news-detail" style="display:none">
    <div class="news-detail">
        <div class="wrapper clearfix">
            <div class="news-pager bottom">
                <div class="time clearfix">
                    <div class="date">{{date}}</div>
                    <div class="like">
                       <span class="heart"></span> ({{like}})
                    </div>
                </div>
                <div class="pager-links clearfix">
                    <div class="links">
                        <div class="pre"><a href="/#/news-detail-pre">Pre</a></div>
                        <div class="next"><a href="/#news-detai-next">Next</a></div>
                    </div>
                    <div class="back">
                        <span>Back</span>
                    </div>
                </div>
                </div>
            <div class="news-detail-left">
                <div class="wrapper clearfix">
                    <div class="news-content top">
                        <div class="img"><img class="img-full" src="/public/misc/images/pictures/news/new-page-avatar.jpg" alt=""></div>
                        <div class="body">
                            <div class="bar">
                                <span class="star"></span>{{title}}
                            </div>
                            <div class="c">
                                <p>{{body}}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="news-detail-right">
                <div class="wrapper">
                    <div class="left">
                        <span class="btn"></span>
                    </div>
                    <div class="slides">
                        <div class="slides-wrapper">
                            {{#slider}}
                            <img class="img-full hideme" src="{{{.}}}" alt="">
                            {{/slider}}
                        </div>
                    </div>
                    <div class="right">
                        <span class="close-btn"></span>
                        <span class="btn"></span></div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="loading">
    
</div>