
<div class="s1 s " id="home" data-stellar-background-ratio="0.2"></div>

<div class="s2 s " id="academy" data-stellar-background-ratio="0.5"></div>

<div class="s2 s3 s " id="program" data-stellar-background-ratio="0.6"></div>

<div class="s4 s2 s " id="residential" data-stellar-background-ratio="0.5"></div>

<div class="s5 s" id="news" data-stellar-background-ratio="0.3"></div>

<div class="s6 s" id="footer" data-stellar-background-ratio="0.5"></div>
