
<!DOCTYPE html>
<html>
<head>
<title>Parallax Scrolling Website</title>
<meta charset="utf-8">

<link rel="icon" type="image/png" href="http://jackrimell.co.uk/assets/img/favicon.png"/>
<script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
<script type="text/javascript" src="/public/scripts/stellar.js"></script>
<script type="text/javascript" src="/public/scripts/waypoints.js"></script>
<script type="text/javascript" src="/public/scripts/easing.js"></script>

<style>
/*CSS Document*/

*{
	margin: 0px;
	padding: 0;
}

html, body{
	width: 100%;
	height: 100%;
	background-color: #333;
}

/* NAV BAR SECTION */

#navigation{
	width: 100%;
	height: 100%;
	float: left;
}
#navBar{
	width: 50px;
	height: 165px;
	position: fixed;
	top: 50%;
	right: 0;
	margin-top: -82.5px;
	z-index:1;
	list-style: none;
}
#navBar li{
	width: 15px;
	height: 15px;
	background-color: ghostwhite;
	border: 5px solid ghostwhite;
	margin: 12.5px;
	cursor: pointer;
	border-radius: 20px;
	transition-duration: 0.7s;
	-webkit-transition-duration: 0.7s;
}
#navBar li:hover, #navBar .current{
	transition-duration: 0.7s;
	-webkit-transition-duration: 0.7s;
	background-color: transparent;
}

/* FOR ALL SLIDES */

.slide{
	background-attachment: fixed;
	width:100%;
	height:100%;
	position: relative;
}

.button{
    display:block;
    width:50px;
    height:50px;
    position:absolute;
    bottom:0px;
    left:50%;
    margin-left: -25px;
    background-color: transparent;
    background-image:url(img/arrow.png);
    background-repeat:no-repeat;
    background-position: center center;
    transition-duration: 0.7s;
	-webkit-transition-duration: 0.7s; /* Safari */
}
.button:hover{
    background-color: rgba(255,255,255,0.6);
    cursor:pointer;
    transition-duration: 0.7s;
	-webkit-transition-duration: 0.7s; /* Safari */
}
.button.last{
	transform:rotate(180deg);
	-ms-transform:rotate(180deg); /* IE 9 */
	-webkit-transform:rotate(180deg); /* Safari and Chrome */
}

/* SLIDES */

#slide1{
	background-color: #2474a9;
}
#slide2{
	background-color: #b33921;
}
#slide3{
	background-color: #1aaf5d;
}
#slide4{
	background-color: #775c93;
}
h1{
	font-family: Verdana, Geneva, sans-serif;
	color: rgba(0,0,0,0.3);
	font-size: 3em;
	position: fixed;
	top: 50%;
	left: 50%;
	margin-left: -235px;
	margin-top: -59px;
	z-index: 1;
}
#ball1{
	width: 200px;
	height: 200px;
	border-radius: 200px;
	position: absolute;
	top: 300px;
	left: 50px;
	background-color: rgba(0,0,0,0.1);
}
#ball2{
	width: 40px;
	height: 40px;
	border-radius: 200px;
	position: absolute;
	top: 80px;
	right: 50px;
	background-color: rgba(0,0,0,0.1);
}
#ball3{
	width: 150px;
	height: 150px;
	border-radius: 200px;
	position: absolute;
	top: 30px;
	right: 200px;
	background-color: rgba(0,0,0,0.1);
}
#ball4{
	width: 40px;
	height: 40px;
	border-radius: 200px;
	position: absolute;
	top: 100px;
	right: 500px;
	background-color: rgba(0,0,0,0.1);
}

#slide4 #ball1{
	width: 200px;
	height: 200px;
	border-radius: 200px;
	position: absolute;
	top: 490px;
	left: 900px;
	background-color: rgba(0,0,0,0.1);
}
#slide4 #ball3{
	width: 200px;
	height: 200px;
	border-radius: 200px;
	position: absolute;
	top: 600px;
	left: 500px;
	background-color: rgba(0,0,0,0.1);
}







</style>

<script>
jQuery(document).ready(function ($) {
	$(window).stellar();
	
	var links = $('#navigation').find('li');
	slide = $('.slide');
	button = $('.button');
	mywindow = $(window);
	htmlbody = $('html,body');
	
	//Setup waypoints plugin
	slide.waypoint(function (event, direction) {
	    //cache the variable of the data-slide attribute associated with each slide
	    dataslide = $(this).attr('data-slide');
	    //If the user scrolls up change the navigation link that has the same data-slide attribute as the slide to active and
	    //remove the active class from the previous navigation link
	    if (direction === 'down') {
	        $('#navigation li[data-slide="' + dataslide + '"]').addClass('current').prev().removeClass('current');
	    }
	    // else If the user scrolls down change the navigation link that has the same data-slide attribute as the slide to active and
	    //remove the active class from the next navigation link
	    else {
	        $('#navigation li[data-slide="' + dataslide + '"]').addClass('current').next().removeClass('current');
	    }
	});
	//waypoints doesnt detect the first slide when user scrolls back up to the top so we add this little bit of code, that removes the class
	//from navigation link slide 2 and adds it to navigation link slide 1.
	mywindow.scroll(function () {
	    if (mywindow.scrollTop() == 0) {
	        $('#navigation li[data-slide="1"]').addClass('current');
	        $('#navigation li[data-slide="2"]').removeClass('current');
	    }
	});
	//Create a function that will be passed a slide number and then will scroll to that slide using jquerys animate. The Jquery
	//easing plugin is also used, so we passed in the easing method of 'easeInOutQuint' which is available throught the plugin.
	function goToByScroll(dataslide) {
	    htmlbody.animate({
	        scrollTop: $('.slide[data-slide="' + dataslide + '"]').offset().top
	    }, 2000, 'easeInOutExpo');
	}
	//When the user clicks on the navigation links, get the data-slide attribute value of the link and pass that variable to the goToByScroll function
	links.click(function (e) {
	    e.preventDefault();
	    dataslide = $(this).attr('data-slide');
	    goToByScroll(dataslide);
	});
	//When the user clicks on the button, get the get the data-slide attribute value of the button and pass that variable to the goToByScroll function
	button.click(function (e) {
	    e.preventDefault();
	    dataslide = $(this).attr('data-slide');
	    goToByScroll(dataslide);
	});
});
</script>

</head>
<body>

<div id="navigation">
	<ul id="navBar">
		<li data-slide="1" class="current"></li>
		<li data-slide="2"></li>
		<li data-slide="3"></li>
		<li data-slide="4"></li>
	</ul>
</div>


	<h1 data-stellar-ratio="0">Parallax Scrolling<br>Website</h1>

<div class="slide" id="slide1" data-slide="1" data-stellar-background-ratio="0.5">
	<a class="button" data-slide="2" title=""></a>
</div>
<div class="slide" id="slide2" data-slide="2" data-stellar-background-ratio="0.5">
	<a class="button" data-slide="3" title=""></a>
</div>
<div class="slide" id="slide3" data-slide="3" data-stellar-background-ratio="0.5">
	<a class="button" data-slide="4" title=""></a>
</div>
<div class="slide" id="slide4" data-slide="4" data-stellar-background-ratio="0.5">
</div>

</body>
</html>