<style type="text/css">
  a {
    color:#A31D3B;
  }
  .right-bar {
    display: none;
  }
  .left-bar {
    display: none;
  }
  .errcon {
    width: 60%;
    margin: auto;
    position: absolute;
    left: 50%;
    margin-left: -30%;
    top: 50%;
    margin-top: -50px;
  }
  
  .err {
    float: left;
    margin-right: 35px;
    font-family: "Plantin Std";
    color: #A31D3B;
    text-align: right;
    width: 30%;
    font-size: 2.5em;
  }
  
  .error-logo {
    position: absolute;
    bottom: 20px;
    right: 20px;
  }
  
  .err-1 {
    float: left;
    width: 60%;
  }
</style>
  
<div class="errcon">
  <div class="err">
    <span>Error</span>
    <span>(404)</span>
  </div>
  <div class="err-1">
    We can’t find the page you’re looking for.Send the <a href="mailto:yca@pku.edu.cn">email</a> to us for help, 
    or head back to <a href="/">home</a>.
  </div>

</div>

<div class="error-logo">
  <img src="/public/misc/images/404_logo.png" alt="" />
</div>

<?php print_r($this->exception);?>

