<?php $modulePath = $this->layout()->modulePath; ?>
<?php echo $this->doctype() ?>
<?php $this->crtuser = Jovial_Controller_Action_Helpers_Login::loginUser();?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Admin Panel</title>

        <!--Styles -->
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/public/admin/components/videojs/video-js.min.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/public/admin/css/default.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/public/admin/css/zice.style.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/public/admin/css/icon.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/public/admin/css/ui-custom.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/public/admin/css/timepicker.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/public/admin/components/colorpicker/css/colorpicker.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/public/admin/components/elfinder/css/elfinder.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/public/admin/components/datatables/dataTables.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/public/admin/components/validationEngine/validationEngine.jquery.css"/>     
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/public/admin/components/jscrollpane/jscrollpane.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/public/admin/components/fancybox/jquery.fancybox.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/public/admin/components/tipsy/tipsy.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/public/admin/components/editor/jquery.cleditor.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/public/admin/components/chosen/chosen.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/public/admin/components/confirm/jquery.confirm.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/public/admin/components/sourcerer/sourcerer.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/public/admin/components/fullcalendar/fullcalendar.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/public/admin/components/Jcrop/jquery.Jcrop.css"/>  
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/public/admin/css/jquery.multiselect.css"/> 
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/public/admin/components/uploadify/uploadify.css"/>   
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/public/admin/js/videojs/video-js.css" />   

<!--[if lte IE 8]><script language="javascript" type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/flot/excanvas.min.js"></script><![endif]-->  

        <!--Script -->
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/js/jquery.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/ui/jquery.ui.min.js"></script> 
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/ui/jquery.multiselect.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/ui/jquery.autotab.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/ui/timepicker.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/colorpicker/js/colorpicker.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/checkboxes/iphone.check.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/elfinder/js/elfinder.full.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/elfinder/js/i18n/elfinder.fr.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/datatables/dataTables.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/datatables/ColVis.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/scrolltop/scrolltopcontrol.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/fancybox/jquery.fancybox.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/jscrollpane/mousewheel.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/jscrollpane/mwheelIntent.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/jscrollpane/jscrollpane.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/spinner/ui.spinner.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/tipsy/jquery.tipsy.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/editor/jquery.cleditor.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/chosen/chosen.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/confirm/jquery.confirm.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/validationEngine/jquery.validationEngine.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/validationEngine/jquery.validationEngine-en.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/vticker/jquery.vticker-min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/sourcerer/sourcerer.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/fullcalendar/fullcalendar.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/flot/flot.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/flot/flot.pie.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/flot/flot.resize.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/flot/graphtable.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/uploadify/uploadify.js"></script>        
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/checkboxes/customInput.jquery.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/effect/jquery-jrumble.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/filestyle/jquery.filestyle.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/placeholder/jquery.placeholder.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/Jcrop/jquery.Jcrop.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/imgTransform/jquery.transform.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/webcam/webcam.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/rating_star/rating_star.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/dualListBox/dualListBox.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/smartWizard/jquery.smartWizard.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/maskedinput/jquery.maskedinput.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/highlightText/highlightText.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/elastic/jquery.elastic.source.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/js/jquery.cookie.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/js/dev.custom.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/ckeditor/ckeditor.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/ckeditor/adapters/jquery.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/videojs/video.dev.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/components/colorbox/jquery.colorbox.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/js/jquery.treeview.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/js/jquery.tokeninput.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/js/zice.custom.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/admin/js/videojs/video.js"></script>
        <script>
          videojs.options.flash.swf = "<?php echo $this->baseUrl(); ?>/public/admin/js/videojs/video-js.swf"
        </script>
        
        <?php echo $this->headScript()?>
    </head>
    <body class="dashborad">
        <div id="alertMessage" class="error"></div>

        <!-- Header -->
        <div id="header" class="clearfix">
            <div class="logo"><img src="<?php echo $this->baseUrl(); ?>/public/admin/images/logo/logo_admin.png"></div>
            <div id="account_info" class="clearfix">
                <div class="setting"><b><?php echo $this->translate('welcome') ?>,</b> <b class="red"><?php if ($this->crtuser) echo $this->crtuser->name; ?></b></div>
                <div class="logout" title="<?php echo $this->translate('logout') ?>">
                    <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'users', 'action' => 'logout'), 'default', true); ?>">
                       <img src="<?php echo $this->baseUrl(); ?>/public/admin/images/connect.png" name="connect" class="disconnect" alt="disconnect" >
                    </a>
                </div> 
            </div>
            
            <!-- 只是多个网站共享一个数据库。 从一个网站跳转到另一个网站是需要LOGOUT再LOGIN。所以这里应该不需要用到 ul li. 
            <div id="websites">
                
                <!--
                <ul>
                    <?php foreach ($this->websitesList() as $website) : ?>
                        <li><a href="<?php echo $this->url(array("website" => $website))?>"><?php echo $website?></a></li>
                    <?php endforeach;?>
                </ul>
            </div>
            -->
            
        </div>
        <!-- End Header -->

        <div id="shadowhead"></div>

        <div id="left_menu">
            <ul id="main_menu" class="main_menu">
                <li class="limenu<?php if ($this->homepageSlideshowsSelected): ?> select<?php endif; ?>"><a href="<?php echo $this->url(array("module" => "admin", "controller" => 'main-slideshows', 'action' => 'index'), 'default', true)?>"><span class="ico gray shadow window"></span><b><?php echo $this->translate("main-slideshows")?></b></a></li>
                <li class="limenu<?php if ($this->brandSelected): ?> select<?php endif; ?>"><a href="<?php echo $this->url(array("module" => "admin", "controller" => 'brand', 'action' => 'index'), 'default', true)?>"><span class="ico gray shadow window"></span><b><?php echo $this->translate("brand")?></b></a></li>
                <li class="limenu<?php if ($this->pageSelected): ?> select<?php endif; ?>"><a href="<?php echo $this->url(array("module" => "admin", "controller" => 'page', 'action' => 'index'), 'default', true)?>"><span class="ico gray shadow window"></span><b><?php echo $this->translate("page")?></b></a></li>
                <li class="limenu<?php if ($this->presentationSelected): ?> select<?php endif; ?>"><a href="<?php echo $this->url(array("module" => "admin", "controller" => 'presentation', 'action' => 'index'), 'default', true)?>"><span class="ico gray shadow window"></span><b><?php echo $this->translate("presentation")?></b></a></li>
                <li class="limenu<?php if ($this->videoSelected): ?> select<?php endif; ?>"><a href="<?php echo $this->url(array("module" => "admin", "controller" => 'video', 'action' => 'index'), 'default', true)?>"><span class="ico gray shadow window"></span><b><?php echo $this->translate("video")?></b></a></li>
                <li class="limenu<?php if ($this->newsSelected): ?> select<?php endif; ?>"><a href="<?php echo $this->url(array("module" => "admin", "controller" => 'news', 'action' => 'index'), 'default', true)?>"><span class="ico gray shadow window"></span><b><?php echo $this->translate("news")?></b></a></li>
                <li class="limenu<?php if ($this->positionSelected): ?> select<?php endif; ?>"><a href="<?php echo $this->url(array("module" => "admin", "controller" => 'position', 'action' => 'index'), 'default', true)?>"><span class="ico gray shadow window"></span><b><?php echo $this->translate("Job Position")?></b></a></li>
                <li class="limenu<?php if ($this->contactSelected): ?> select<?php endif; ?>"><a href="<?php echo $this->url(array("module" => "admin", "controller" => 'contact', 'action' => 'index'), 'default', true)?>"><span class="ico gray shadow window"></span><b><?php echo $this->translate("contact")?></b></a></li>
            </ul>
        </div>

        <div id="content">
            <div class="inner">
                <div class="topcolumn">
                    <ul id="shortcut">
                        <li> <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'dashboard'), 'default', true); ?>" title="Back To home"> <img src="<?php echo $this->baseUrl(); ?>/public/admin/images/icon/shortcut/home.png" alt="home"/><strong>Home</strong> </a> </li>
                    </ul>

                    <div class="clear"></div>
                </div>
                <div class="clear"></div>

                <!-- full width -->
                <?php echo $this->layout()->content; ?>

                <!-- clear fix -->
                <div class="clear"></div>

                <div id="footer"> 
                    <div class="left">&copy; Copyright 2013  All Rights Reserved <span class="tip"><a  href="http://www.c3o.asia/" target="_blank" title="C3O Limited" >C3O Limited</a> </span></div> 
                    <div class="right">
                        <div id="languages">
                            <?php $languages = Jovial_Translate_Translate::getLangauges(); ?>
                                <?php foreach ($languages as $code => $name): ?>
                                    <span class="tip txt-right" >
                                        <a class="lang-code" code="<?php echo $code?>" href="<?php echo $this->url()?>" title="<?php echo $this->translate($name) ?>"><?php echo $this->translate($name) ?></a>
                                    </span>
                                <?php endforeach;?>
                        </div>
                    </div>
                </div>

            </div> <!--// End inner -->
        </div> <!--// End content --> 
    </body>
</html>
